testing ci/cd

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -41,4 +41,13 @@ jobs:
             whoami
             pwd
             echo "Current Directory Contents:"
-
+            ls -la
+            
+            # Navigate to your project directory on Hostinger
+            cd /home/u824026742/domains/PreBuilds
+            
+            # Execute the deploy.sh script
+            echo "Executing deploy.sh script..."
+            ./deploy.sh || { echo "Deploy failed!"; exit 1; }
+            
+            echo "Deployment Completed"
